package media

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// Storage holds image bytes. FSStorage serves one machine; an S3/R2
// implementation can replace it when the API runs on several instances.
type Storage interface {
	Put(ctx context.Context, key string, data []byte) error
	Open(ctx context.Context, key string) (io.ReadCloser, error)
	Delete(ctx context.Context, key string) error
}

type FSStorage struct {
	dir string
}

func NewFSStorage(dir string) (*FSStorage, error) {
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return nil, fmt.Errorf("create storage dir: %w", err)
	}
	return &FSStorage{dir: dir}, nil
}

// path maps a key to a file inside dir. Keys are generated by this package
// (room and image UUIDs), never taken from a request.
func (s *FSStorage) path(key string) string {
	return filepath.Join(s.dir, filepath.FromSlash(key))
}

func (s *FSStorage) Put(_ context.Context, key string, data []byte) error {
	p := s.path(key)
	if err := os.MkdirAll(filepath.Dir(p), 0o750); err != nil {
		return fmt.Errorf("put %s: %w", key, err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(p), ".upload-*")
	if err != nil {
		return fmt.Errorf("put %s: %w", key, err)
	}
	defer func() { _ = os.Remove(tmp.Name()) }()
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("put %s: %w", key, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("put %s: %w", key, err)
	}
	if err := os.Rename(tmp.Name(), p); err != nil {
		return fmt.Errorf("put %s: %w", key, err)
	}
	return nil
}

func (s *FSStorage) Open(_ context.Context, key string) (io.ReadCloser, error) {
	f, err := os.Open(s.path(key))
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", key, err)
	}
	return f, nil
}

func (s *FSStorage) Delete(_ context.Context, key string) error {
	if err := os.Remove(s.path(key)); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("delete %s: %w", key, err)
	}
	return nil
}
